[script://$SPLUNK_HOME/etc/apps/splunk4champions2/bin/download_weatherdata.py]
python.version = python3
disabled = false
index = main
interval = -1
source = s4c-weather-script
sourcetype = syslog

[script://$SPLUNK_HOME/etc/apps/splunk4champions2/bin/download_weatherdata24.py]
python.version = python3
disabled = false
index = main
interval = -1
source = s4c-weather24-script
sourcetype = syslog

[script://$SPLUNK_HOME/etc/apps/splunk4champions2/bin/download_wwwdata.py]
python.version = python3
disabled = false
index = main
interval = -1
source = s4c-www-script
sourcetype = syslog

[script://$SPLUNK_HOME/etc/apps/splunk4champions2/bin/update_wwwdata.py]
python.version = python3
disabled = false
index = main
interval = -1
source = s4c-www_live-script
sourcetype = syslog

[script://$SPLUNK_HOME/etc/apps/splunk4champions2/bin/download_tutorialdata.py]
python.version = python3
disabled = false
index = main
interval = -1
source = s4c-tutorial-script
sourcetype = syslog

[monitor:///var/log/current.log]
disabled = false
index = s4c_weather
sourcetype = s4c:weather

[script://./bin/open_meteo_weather.py metrics]
disabled   = 0
interval   = 300
index      = s4c_meteo_metrics
sourcetype = open_meteo:weather:metric
source     = open-meteo
host       = $decideOnStartup

[script://./bin/open_meteo_weather.py events]
disabled   = 0
interval   = 300
index      = s4c_meteo
sourcetype = open_meteo:weather:json
source     = open-meteo
host       = $decideOnStartup%
