#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

APP1="https://github.com/bautt/s4cshow/raw/main/splunk4champions2.tar.gz"
APP2="https://github.com/bautt/s4cshow/raw/main/phyphox.tar.gz"

TMPFILE1="/tmp/splunk4champions2.tar.gz"
TMPFILE2="/tmp/phyphox.tar.gz"

INDEXES="https://raw.githubusercontent.com/bautt/s4cshow/main/indexes.conf"
INPUTS="https://raw.githubusercontent.com/bautt/s4cshow/main/inputs.conf"

LOGFILE="/var/log/s4c.log"

log() {
    echo "$(/bin/date +'%Y-%m-%d %H:%M:%S') - $1" | /usr/bin/tee -a "$LOGFILE"
}

install_app() {
    local app_url="$1"
    local tmp_file="$2"

    log "Downloading app from $app_url."
    if /usr/bin/wget -q "$app_url" -O "$tmp_file"; then
        log "Successfully downloaded $tmp_file."
        if /usr/bin/tar zxf "$tmp_file" --directory /opt/splunk/etc/apps; then
            log "Successfully extracted $tmp_file."
        else
            log "Failed to extract $tmp_file."
        fi
    else
        log "Failed to download $app_url."
    fi
}

# Install apps
install_app "$APP1" "$TMPFILE1"
install_app "$APP2" "$TMPFILE2"

# Create indexes
log "Setting up index and input configurations."
/usr/bin/mkdir -p /opt/splunk/etc/apps/splunk4champions2/local && \
/usr/bin/wget -q "$INDEXES" -O /opt/splunk/etc/apps/splunk4champions2/local/indexes.conf && \
/usr/bin/wget -q "$INPUTS" -O /opt/splunk/etc/apps/splunk4champions2/local/inputs.conf && \
log "Configuration files set up successfully."

# Restart Splunk
log "Restarting Splunk as splunk user."
if /bin/su - splunk -c '/opt/splunk/bin/splunk restart' >>"$LOGFILE" 2>&1; then
    log "Splunk restarted successfully."
else
    log "Failed to restart Splunk."
fi